# Generated by Django 2.2.1 on 2019-05-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_token_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='identitytoken',
            options={'ordering': ['create_date'], 'verbose_name_plural': 'Token di accesso'},
        ),
        migrations.AddField(
            model_name='identity',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='identity',
            name='tin',
            field=models.CharField(blank=True, help_text='Taxpayer Identification Number (codice fiscale)', max_length=24, null=True),
        ),
    ]
