# Generated by Django 2.2.1 on 2019-05-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_token_auth', '0002_auto_20190529_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
